# Re-usable GitHub Action that runs Django system checks.
# Args:
#   deploy[str]: whether to run Django checks with `--deploy` flag
#
# Usage:
#   ```
#   steps:
#     - uses: ./.github/actions/django-checks
#       with:
#         deploy: true|false
#   ```

name: 'django-checks'
description: 'Run Django system checks'

inputs:
  deploy:
    description: 'Run checks in deploy mode'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.2"
        enable-cache: true
    - uses: extractions/setup-just@v3
    - run: |
        # write out all lines in .env _except_ the insecure default SECRET_KEY and
        # generate a new, secure secret key and append it to .env
        if [[ "${{ inputs.deploy }}" == "true" ]]; then
            cp _deploy/.env.deploy .env
            grep -v '^SECRET_KEY=' .env > .env.tmp && mv .env.tmp .env
            printf 'SECRET_KEY=%s\n' "$(tr -dc 'a-zA-Z0-9!@#$%^&*(-_=+)' < /dev/urandom | head -c 50)" >> .env
            PYTHONDEVMODE=1 just manage check --deploy --fail-level WARNING
        else
            cp .env.in .env
            PYTHONDEVMODE=1 just manage check
        fi
      shell: bash
