site_name: Djereo documentation
docs_dir: src
site_url: https://albertomh.github.io/djereo/
site_description: Documentation for djereo, a Django project template.
site_author: Alberto Morón Hernández
extra_css:
    - css/extra.css
nav:
  - Home: index.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
    logo: media/djereo_wordmark-logo.webp
