# Run checks and test suite.
#
# Usage:
# ```
# jobs:
#   checks:
#     uses: ./.github/workflows/_checks.yaml
# ```
name: Checks

on:
  workflow_call:

jobs:
  pre_commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/pre-commit

  generate-nox-py-versions:
    needs:
      - pre_commit
    runs-on: ubuntu-24.04
    outputs:
      py_version: ${{ steps.set-matrix.outputs.py_version }}
    steps:
    - uses: actions/checkout@v5
    - uses: wntrblm/nox@main
    - id: set-matrix
      shell: bash
      run: |
        # Extract Python versions from nox session names (both selected and skipped)
        # into a JSON array. Session lines start with '*' or '-'.
        py_version_json="$(
        nox --list \
            | grep -E '^[*-] ' \
            | cut -d' ' -f2 \
            | sed 's/^tests-//' \
            | jq -R -s -c 'split("\n")[:-1]'
        )"
        echo "py_version=$py_version_json" >> "$GITHUB_OUTPUT"

  test:
    needs:
      - generate-nox-py-versions
    strategy:
      fail-fast: false
      matrix:
        py_version: ${{ fromJson(needs.generate-nox-py-versions.outputs.py_version) }}
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.17"
      # Not redundant! Must be installed since used by integration tests in the next step.
      - uses: extractions/setup-just@v3
      - uses: wntrblm/nox@2025.05.01
        with:
          python-versions: "${{ matrix.py_version }}"
      - run: nox --session "tests-${{ matrix.py_version }}"
