# Run checks and test suite.
#
# Usage:
# ```
# jobs:
#   checks:
#     uses: ./.github/workflows/_checks.yaml
# ```
name: Checks

on:
  workflow_call:

jobs:
  pre_commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prek

  generate-nox-py-versions:
    runs-on: ubuntu-24.04
    outputs:
      nox_sessions: ${{ steps.set-matrix.outputs.nox_sessions }}
    steps:
    - uses: actions/checkout@v6
    - name: Cache nox Python versions list
      id: cache-nox-py-versions
      uses: actions/cache@v5
      with:
        path: .nox-py-versions.json
        key: nox-py-versions-${{ runner.os }}-${{ hashFiles('noxfile.py', 'pyproject.toml') }}
    - uses: wntrblm/nox@2026.02.09
      if: steps.cache-nox-py-versions.outputs.cache-hit != 'true'
    - id: set-matrix
      shell: bash
      env:
        CACHE_PY_VERSIONS_HIT: ${{ steps.cache-nox-py-versions.outputs.cache-hit }}
      run: |
        # Extract sessions from nox list into a JSON array.
        # Session lines start with '*' or '-'.
        if [[ $CACHE_PY_VERSIONS_HIT == "true" ]]; then
          nox_sessions_json="$(cat .nox-py-versions.json)"
        else
          nox_sessions_json="$(
            nox --list \
              | grep -E '^[*-] ' \
              | cut -d' ' -f2 \
              | sed 's/^tests-//' \
              | jq -R -s -c 'split("\n")[:-1]'
          )"
          echo "$nox_sessions_json" > .nox-py-versions.json
        fi
        echo "nox_sessions=$nox_sessions_json" >> "$GITHUB_OUTPUT"

  test:
    needs:
      - pre_commit
      - generate-nox-py-versions
    strategy:
      fail-fast: false
      matrix:
        nox_session: ${{ fromJson(needs.generate-nox-py-versions.outputs.nox_sessions) }}
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.11"
          enable-cache: true
      # Not redundant! Must be installed since used by integration tests in the next step.
      - uses: extractions/setup-just@v3
      - name: Extract Python version
        id: py-version
        shell: bash
        run: |
          # Extract 3.13 from 3.13(django='5.2')
          PY_VER=$(echo "${{ matrix.nox_session }}" | cut -d'(' -f1)
          echo "version=$PY_VER" >> "$GITHUB_OUTPUT"
      - uses: wntrblm/nox@2026.02.09
        with:
          python-versions: "${{ steps.py-version.outputs.version }}"
      - run: nox --session "tests-${{ matrix.nox_session }}"
