# djereo Continuous Integration pipeline
# Runs when a Pull Request is merged into the 'main' branch.
name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  build-docs:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # for `mkdocs gh-deploy`
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/publish-docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
